import { randomBytes } from "node:crypto";
import type { Response } from "express";

export function emailPage(res: Response, reset: boolean) {
  const nonce = randomBytes(18).toString("base64");
  res.set({
    "Cache-Control": "no-store",
    "Referrer-Policy": "no-referrer",
    "X-Content-Type-Options": "nosniff",
    "Content-Security-Policy": `default-src 'none'; script-src 'nonce-${nonce}'; style-src 'nonce-${nonce}'; connect-src 'self'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'`,
  });
  res.type("html")
    .send(`<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light"><title>${reset ? "Đặt lại mật khẩu" : "Xác minh email"} · N8 Cineplex</title>
<style nonce="${nonce}">*{box-sizing:border-box}body{margin:0;min-height:100vh;background:#F5F3F0;color:#25232A;font:16px/1.5 Arial,Helvetica,sans-serif;display:grid;place-items:center;padding:32px 16px}.card{width:100%;max-width:480px;background:#fff;border:1px solid #D9D3D6;border-radius:16px;padding:32px;box-shadow:0 12px 40px #25232A08}.brand{font-size:20px;font-weight:700;letter-spacing:1px;color:#7B263D}.eyebrow{margin:24px 0 8px;color:#625D65;font-size:12px;letter-spacing:1.5px;text-transform:uppercase}h1{font:700 32px/1.2 Georgia,'Times New Roman',serif;margin:0 0 16px}.intro{color:#625D65;margin:0 0 24px}label{display:block;font-weight:600;margin:20px 0 0}input,button{display:block;width:100%;min-height:56px;border-radius:12px;font:inherit}input{border:1px solid #D9D3D6;background:#fff;color:#25232A;padding:14px 16px;margin:8px 0 0}input:focus{border-color:#7B263D}input:focus-visible,button:focus-visible{outline:3px solid #7B263D;outline-offset:3px}button{border:0;background:#7B263D;color:#fff;font-weight:600;padding:14px 20px;margin:24px 0 0;cursor:pointer}button:hover:not(:disabled),button:active:not(:disabled){background:#5C1C2E}button:disabled{opacity:.65;cursor:wait}.hint,.footer{color:#625D65;font-size:13px}.hint{margin:16px 0 0}.footer{border-top:1px solid #D9D3D6;margin:24px 0 0;padding:20px 0 0}#result{white-space:pre-wrap;overflow-wrap:anywhere;color:#A12835}#result:empty{display:none}#result[data-state="success"]{color:#246345}@media(max-width:400px){.card{padding:24px}h1{font-size:28px}}</style></head><body>
<main class="card"><div class="brand">N8 CINEPLEX</div><p class="eyebrow">Tài khoản của bạn</p><h1>${reset ? "Đặt lại mật khẩu" : "Xác minh email"}</h1><p class="intro">${reset ? "Tạo mật khẩu mới để tiếp tục trải nghiệm cùng N8 Cineplex." : "Chỉ còn một bước để hoàn tất thao tác bạn đã yêu cầu."}</p><form id="form">${reset ? '<label for="password">Mật khẩu mới</label><input id="password" type="password" autocomplete="new-password" minlength="8" maxlength="128" aria-describedby="hint" required><label for="confirm">Xác nhận mật khẩu</label><input id="confirm" type="password" autocomplete="new-password" minlength="8" maxlength="128" required><p id="hint" class="hint">Dùng từ 8 đến 128 ký tự. Không chia sẻ mật khẩu với người khác.</p>' : '<p class="hint">Bấm xác nhận để xác minh địa chỉ email. Việc mở trang chưa thay đổi tài khoản.</p>'}<button id="button">${reset ? "Đặt mật khẩu mới" : "Xác nhận email"}</button></form><p id="result" role="status" aria-live="polite"></p><p class="footer">Sau khi hoàn tất, hãy quay lại ứng dụng N8 Cineplex.<br>Nếu bạn không yêu cầu thao tác này, hãy đóng trang.</p></main>
<script nonce="${nonce}">let token='';try{token=decodeURIComponent(location.hash.slice(1));}catch{}history.replaceState(null,'',location.pathname);const form=document.getElementById('form'),button=document.getElementById('button'),result=document.getElementById('result');form.addEventListener('submit',async e=>{e.preventDefault();result.dataset.state='error';if(!token){result.textContent='Liên kết không hợp lệ. Hãy yêu cầu email mới.';return;}const body={token};${reset ? "const p=document.getElementById('password'),c=document.getElementById('confirm');if(p.value!==c.value){result.textContent='Xác nhận mật khẩu không khớp.';return;}body.newPassword=p.value;" : ""}button.disabled=true;try{const r=await fetch(location.pathname,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();result.textContent=Array.isArray(data.message)?data.message.join('\\n'):data.message||'Không thực hiện được.';result.dataset.state=r.ok?'success':'error';if(r.ok)form.remove();}catch{result.textContent='Lỗi mạng. Hãy thử lại.';}finally{button.disabled=false;${reset ? "document.getElementById('password')?.value && (document.getElementById('password').value='');document.getElementById('confirm')?.value && (document.getElementById('confirm').value='');" : ""}}});</script></body></html>`);
}
